-- Agrega TIPO y TELEFONO a la tabla EMPLEADOS
IF NOT EXISTS (
  SELECT 1 FROM sys.columns
  WHERE object_id = OBJECT_ID(N'EMPLEADOS') AND name = 'TIPO'
)
BEGIN
  ALTER TABLE EMPLEADOS ADD TIPO VARCHAR(150) NULL;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.columns
  WHERE object_id = OBJECT_ID(N'EMPLEADOS') AND name = 'TELEFONO'
)
BEGIN
  ALTER TABLE EMPLEADOS ADD TELEFONO VARCHAR(50) NULL;
END;
